"""DM847 module 8: de novo motif discovery with entropy models and EM."""

from __future__ import annotations

from ...i18n import AppLocale
from ..localized_models import LocalizedLearningModule
from ..models import AssessmentItem, LearningModule
from .standard import StandardModuleSpec, build_module, build_question_bank, materialize_bank

_SPEC = StandardModuleSpec(
    module_id="dm847.m08",
    title=("Descubrimiento de motivos con entropía y EM", "Motif discovery with entropy and EM", "Motivopdagelse med entropi og EM"),
    summary=("Modela motivos de secuencia mediante PWM y log-odds, cuantifica conservación con entropía, aplica EM a posiciones latentes y valida enriquecimiento, estabilidad y sesgos del fondo.", "Model sequence motifs with PWMs and log-odds, quantify conservation with entropy, apply EM to latent positions, and validate enrichment, stability, and background bias.", "Modellér sekvensmotiver med PWM og log-odds, kvantificér konservering med entropi, anvend EM på latente positioner og validér berigelse, stabilitet og baggrundsbias."),
    objectives=(
        ("m08.o1", ("Construir matrices de frecuencia y PWM con pseudoconteos.", "Build frequency matrices and PWMs with pseudocounts.", "Bygge frekvensmatricer og PWM'er med pseudotællinger.")),
        ("m08.o2", ("Interpretar entropía e información por posición.", "Interpret positional entropy and information.", "Fortolke positionsentropi og information.")),
        ("m08.o3", ("Puntuar ventanas mediante log-odds frente a un fondo.", "Score windows with log-odds against a background.", "Score vinduer med log-odds mod en baggrund.")),
        ("m08.o4", ("Formular variables latentes y pasos E/M en descubrimiento de motivos.", "Formulate latent variables and E/M steps in motif discovery.", "Formulere latente variable og E/M-trin i motivopdagelse.")),
        ("m08.o5", ("Reconocer óptimos locales, anchura y número de motivos como decisiones.", "Recognize local optima, width, and motif count as decisions.", "Genkende lokale optima, bredde og antal motiver som beslutninger.")),
        ("m08.o6", ("Validar motivos con secuencias retenidas, nulos y evidencia externa.", "Validate motifs with held-out sequences, nulls, and external evidence.", "Validere motiver med hold-out-sekvenser, nulmodeller og ekstern evidens.")),
    ),
    concepts=(
        ("pwm", ("PWM y pseudoconteos", "PWMs and pseudocounts", "PWM'er og pseudotællinger"), ("Una PWM contiene una distribución de bases por posición. Se estima a partir de sitios alineados y pseudoconteos que evitan probabilidades cero. La elección del pseudoconteo expresa regularización y afecta motivos con pocos ejemplos.", "A PWM contains a base distribution at each position. It is estimated from aligned sites with pseudocounts that avoid zero probabilities. Pseudocount choice expresses regularization and affects motifs with few examples.", "En PWM indeholder en basefordeling ved hver position. Den estimeres fra alignede sites med pseudotællinger, der undgår nulsandsynligheder. Valget af pseudotælling udtrykker regularisering og påvirker motiver med få eksempler."), (("Cada columna debe sumar uno.", "Each column should sum to one.", "Hver kolonne bør summere til én."), ("Pseudoconteos controlan ceros y sobreajuste.", "Pseudocounts control zeros and overfitting.", "Pseudotællinger kontrollerer nuller og overfitting."))),
        ("entropy", ("Entropía e información", "Entropy and information", "Entropi og information"), ("La entropía de Shannon es máxima cuando las bases son equiprobables y baja cuando una posición está conservada. La información suele compararse con la entropía máxima o con un fondo no uniforme. Un logo de secuencia visualiza información total y composición, pero no prueba función.", "Shannon entropy is maximal when bases are equally probable and low when a position is conserved. Information is commonly compared with maximum entropy or a nonuniform background. A sequence logo visualizes total information and composition but does not prove function.", "Shannon-entropi er maksimal, når baser er lige sandsynlige, og lav, når en position er konserveret. Information sammenlignes ofte med maksimal entropi eller en ikke-uniform baggrund. Et sekvenslogo visualiserer total information og sammensætning, men beviser ikke funktion."), (("Conservación alta implica entropía baja.", "High conservation implies low entropy.", "Høj konservering indebærer lav entropi."), ("El fondo puede no ser 0.25 por base.", "Background may not be 0.25 per base.", "Baggrunden er måske ikke 0,25 pr. base."))),
        ("log-odds", ("Score de ventanas", "Window scoring", "Scoring af vinduer"), ("El score de una ventana suma log(PWM/base de fondo) por posición. Valores altos indican mayor compatibilidad relativa con el motivo. La orientación inversa, bases ambiguas y dependencia entre posiciones requieren políticas explícitas.", "A window score sums log(PWM/background base probability) across positions. High values indicate stronger relative compatibility with the motif. Reverse orientation, ambiguous bases, and dependence between positions require explicit policies.", "En vinduesscore summerer log(PWM/baggrundssandsynlighed) over positioner. Høje værdier indikerer stærkere relativ kompatibilitet med motivet. Omvendt orientering, tvetydige baser og afhængighed mellem positioner kræver eksplicitte politikker."), (("El score es relativo al fondo.", "Score is relative to background.", "Scoren er relativ til baggrunden."), ("Una PWM estándar asume independencia posicional.", "A standard PWM assumes positional independence.", "En standard-PWM antager positionsuafhængighed."))),
        ("latent-sites", ("Posiciones latentes", "Latent motif positions", "Latente motivpositioner"), ("En secuencia puede contener un sitio desconocido, ninguno o varios según el modelo. La posición del sitio es una variable latente. OOPS, ZOOPS y TCM representan un sitio por secuencia, cero o uno, y múltiples ocurrencias, respectivamente.", "A sequence may contain one unknown site, none, or several depending on the model. Site position is a latent variable. OOPS, ZOOPS, and TCM represent one site per sequence, zero or one, and multiple occurrences, respectively.", "En sekvens kan indeholde ét ukendt site, ingen eller flere afhængigt af modellen. Site-positionen er en latent variabel. OOPS, ZOOPS og TCM repræsenterer henholdsvis ét site pr. sekvens, nul eller ét og flere forekomster."), (("El modelo de ocurrencia debe corresponder al experimento.", "Occurrence model should match the experiment.", "Forekomstmodellen bør passe til eksperimentet."), ("Forzar un sitio puede inventar señales.", "Forcing one site may invent signals.", "At tvinge ét site kan opfinde signaler."))),
        ("em", ("EM para motivos", "EM for motifs", "EM for motiver"), ("En E-step calcula responsabilidades para posiciones candidatas usando el motivo actual y el fondo. El M-step actualiza PWM y mezcla a partir de conteos esperados. La likelihood no disminuye, pero la solución depende de inicialización, anchura y modelo de ocurrencia.", "The E-step computes responsibilities for candidate positions using the current motif and background. The M-step updates the PWM and mixture from expected counts. Likelihood does not decrease, but the solution depends on initialization, width, and occurrence model.", "E-trinnet beregner ansvar for kandidatpositioner med det aktuelle motiv og baggrunden. M-trinnet opdaterer PWM og blanding fra forventede tællinger. Likelihood falder ikke, men løsningen afhænger af initialisering, bredde og forekomstmodel."), (("EM mejora localmente la likelihood.", "EM improves likelihood locally.", "EM forbedrer likelihood lokalt."), ("Múltiples reinicios son necesarios.", "Multiple restarts are necessary.", "Flere genstarter er nødvendige."))),
        ("validation", ("Selección y validación", "Selection and validation", "Selektion og validering"), ("Anchura, número de motivos y fondo pueden seleccionarse con datos retenidos, criterios penalizados o estabilidad. La validación incluye enriquecimiento frente a secuencias control, recuperación de sitios conocidos, reproducibilidad entre reinicios y evidencia independiente como ChIP-seq o conservación.", "Width, motif count, and background can be selected with held-out data, penalized criteria, or stability. Validation includes enrichment against control sequences, recovery of known sites, reproducibility across restarts, and independent evidence such as ChIP-seq or conservation.", "Bredde, antal motiver og baggrund kan vælges med hold-out-data, penaliserede kriterier eller stabilitet. Validering omfatter berigelse mod kontrolsekvenser, gendannelse af kendte sites, reproducerbarhed mellem genstarter og uafhængig evidens som ChIP-seq eller konservering."), (("La mejor likelihood de entrenamiento puede sobreajustar.", "Best training likelihood may overfit.", "Bedste trænings-likelihood kan overfitte."), ("Motivos de baja complejidad requieren controles.", "Low-complexity motifs require controls.", "Motiver med lav kompleksitet kræver kontroller."))),
    ),
    examples=(
        ("m08.e01", ("PWM con pseudoconteo", "PWM with pseudocount", "PWM med pseudotælling"), ("Estima una columna a partir de conteos A=3,C=1,G=0,T=0 y pseudoconteo 1.", "Estimate a column from counts A=3,C=1,G=0,T=0 and pseudocount 1.", "Estimér en kolonne fra tællinger A=3,C=1,G=0,T=0 og pseudotælling 1."), (("Suma uno a cada base.", "Add one to each base.", "Læg én til hver base."), ("Normaliza por el total ajustado.", "Normalize by adjusted total.", "Normalisér med den justerede total.")), """def pwm_column(counts: dict[str, int], pseudocount: float = 1.0) -> dict[str, float]:\n    alphabet = \"ACGT\"\n    total = sum(counts.get(base, 0) + pseudocount for base in alphabet)\n    return {base: (counts.get(base, 0) + pseudocount) / total for base in alphabet}\n\n\nprint(pwm_column({\"A\": 3, \"C\": 1, \"G\": 0, \"T\": 0}))\n""", "{'A': 0.5, 'C': 0.25, 'G': 0.125, 'T': 0.125}", ("El pseudoconteo evita declarar G o T imposibles.", "The pseudocount avoids declaring G or T impossible.", "Pseudotællingen undgår at erklære G eller T umulige.")),
        ("m08.e02", ("Información por posición", "Information per position", "Information pr. position"), ("Calcula bits respecto a fondo uniforme.", "Compute bits relative to uniform background.", "Beregn bits relativt til uniform baggrund."), (("Entropía usa -p log2 p.", "Entropy uses -p log2 p.", "Entropi bruger -p log2 p."), ("Para ADN uniforme, máximo es 2 bits.", "For uniform DNA, maximum is 2 bits.", "For uniformt DNA er maksimum 2 bits.")), """from math import log2\n\n\ndef information_bits(probabilities: list[float]) -> float:\n    entropy = -sum(value * log2(value) for value in probabilities if value > 0)\n    return 2.0 - entropy\n\n\nprint(round(information_bits([0.7, 0.1, 0.1, 0.1]), 3))\n""", "0.643", ("La columna está parcialmente conservada, no completamente determinada.", "The column is partly conserved, not fully determined.", "Kolonnen er delvist konserveret, ikke fuldt bestemt.")),
        ("m08.e03", ("Responsabilidades normalizadas", "Normalized responsibilities", "Normaliserede ansvar"), ("Convierte scores logarítmicos de posiciones candidatas en probabilidades estables.", "Convert log scores of candidate positions into stable probabilities.", "Omsæt logscores for kandidatpositioner til stabile sandsynligheder."), (("Resta el máximo para estabilidad.", "Subtract the maximum for stability.", "Træk maksimum fra for stabilitet."), ("Normaliza exponentes.", "Normalize exponentials.", "Normalisér eksponentialer.")), """from math import exp\n\n\ndef softmax(log_scores: list[float]) -> list[float]:\n    maximum = max(log_scores)\n    weights = [exp(score - maximum) for score in log_scores]\n    total = sum(weights)\n    return [weight / total for weight in weights]\n\n\nprint([round(value, 3) for value in softmax([1.0, 2.0, 0.0])])\n""", "[0.245, 0.665, 0.09]", ("Estas responsabilidades pueden alimentar los conteos esperados del M-step.", "These responsibilities can feed expected counts in the M-step.", "Disse ansvar kan indgå i de forventede tællinger i M-trinnet.")),
    ),
    practices=(
        ("m08.p01", "CODE_TRACING", ("Con cuatro bases equiprobables, ¿cuál es la entropía?", "With four equiprobable bases, what is entropy?", "Med fire lige sandsynlige baser, hvad er entropien?"), (("log2(4).", "Use log2(4).", "Brug log2(4)."),), ("2 bits", "2 bits", "2 bits"), ("Es la entropía máxima para ADN canónico.", "It is maximum entropy for canonical DNA.", "Det er maksimal entropi for kanonisk DNA."), ""),
        ("m08.p02", "SHORT_ANSWER", ("Explica por qué se usan pseudoconteos.", "Explain why pseudocounts are used.", "Forklar hvorfor pseudotællinger bruges."), (("Piensa en ceros y regularización.", "Think zeros and regularization.", "Tænk på nuller og regularisering."),), ("Evitan probabilidades cero por muestreo limitado y reducen sobreajuste; su magnitud controla cuánto se aproxima la PWM al prior.", "They avoid zero probabilities from limited sampling and reduce overfitting; magnitude controls shrinkage toward the prior.", "De undgår nulsandsynligheder fra begrænset sampling og reducerer overfitting; størrelsen styrer shrinkage mod prioren."), ("Deben declararse y evaluarse.", "They should be declared and evaluated.", "De bør erklæres og evalueres."), ""),
        ("m08.p03", "FILL_IN_THE_BLANK", ("El modelo que permite cero o un sitio por secuencia se llama ____.", "The model allowing zero or one site per sequence is called ____.", "Modellen, der tillader nul eller ét site pr. sekvens, kaldes ____."), (("Acrónimo de zero or one occurrence.", "Acronym for zero or one occurrence.", "Akronym for zero or one occurrence."),), ("ZOOPS", "ZOOPS", "ZOOPS"), ("OOPS obliga exactamente uno.", "OOPS forces exactly one.", "OOPS tvinger præcis ét."), ""),
        ("m08.p04", "DATA_INTERPRETATION", ("EM converge a motivos distintos según inicialización. Interpreta.", "EM converges to different motifs by initialization. Interpret.", "EM konvergerer til forskellige motiver afhængigt af initialisering. Fortolk."), (("Óptimos locales.", "Local optima.", "Lokale optima."),), ("La likelihood tiene varios óptimos locales; ejecutar reinicios, comparar likelihood retenida, estabilidad y evidencia externa en lugar de elegir una ejecución arbitraria.", "Likelihood has multiple local optima; run restarts and compare held-out likelihood, stability, and external evidence rather than choosing one run arbitrarily.", "Likelihood har flere lokale optima; kør genstarter og sammenlign hold-out-likelihood, stabilitet og ekstern evidens frem for at vælge én kørsel vilkårligt."), ("La reproducibilidad entre reinicios es diagnóstico.", "Reproducibility across restarts is diagnostic.", "Reproducerbarhed mellem genstarter er diagnostisk."), ""),
        ("m08.p05", "PIPELINE_DESIGN", ("Diseña un fondo para promotores ricos en GC.", "Design a background for GC-rich promoters.", "Design en baggrund for GC-rige promotorer."), (("No uses necesariamente 0.25.", "Do not necessarily use 0.25.", "Brug ikke nødvendigvis 0,25."),), ("Estimar frecuencias o un Markov de orden bajo desde secuencias control/promotores, separado de sitios positivos; evaluar si conserva dinucleótidos y comparar varios fondos.", "Estimate frequencies or a low-order Markov model from control/promoter sequences separate from positives; assess dinucleotide preservation and compare backgrounds.", "Estimér frekvenser eller en lavordens Markov-model fra kontrol-/promotorsekvenser adskilt fra positive; vurder bevarelse af dinukleotider og sammenlign baggrunde."), ("Un fondo incorrecto produce motivos de composición.", "A wrong background produces composition motifs.", "En forkert baggrund producerer sammensætningsmotiver."), ""),
        ("m08.p06", "DEBUGGING", ("Una PWM asigna probabilidad cero a una base rara y genera -inf. Corrige.", "A PWM assigns zero probability to a rare base and yields -inf. Correct it.", "En PWM tildeler nul sandsynlighed til en sjælden base og giver -inf. Ret den."), (("Añade prior.", "Add a prior.", "Tilføj prior."),), ("Usar pseudoconteos positivos, renormalizar columnas y documentar el prior; comprobar que cada columna suma uno.", "Use positive pseudocounts, renormalize columns, and document the prior; check every column sums to one.", "Brug positive pseudotællinger, normalisér kolonner og dokumentér prioren; kontrollér at hver kolonne summerer til én."), ("Cero observado no implica evento imposible.", "Observed zero does not imply an impossible event.", "Observeret nul indebærer ikke en umulig hændelse."), ""),
        ("m08.p07", "ORAL_EXPLANATION", ("Explica E-step y M-step para OOPS.", "Explain E-step and M-step for OOPS.", "Forklar E-trin og M-trin for OOPS."), (("Una posición por secuencia.", "One position per sequence.", "Én position pr. sekvens."),), ("E-step calcula probabilidad posterior de cada posición candidata en cada secuencia; M-step suma bases ponderadas por esas responsabilidades y renormaliza la PWM y parámetros de fondo.", "The E-step computes posterior probability for each candidate position in each sequence; the M-step sums bases weighted by responsibilities and renormalizes PWM and background parameters.", "E-trinnet beregner posterior sandsynlighed for hver kandidatposition i hver sekvens; M-trinnet summerer baser vægtet med ansvar og normaliserer PWM og baggrundsparametre."), ("La restricción OOPS normaliza dentro de cada secuencia.", "The OOPS constraint normalizes within each sequence.", "OOPS-begrænsningen normaliserer inden for hver sekvens."), ""),
        ("m08.p08", "ORDERING", ("Ordena: separar train/test, elegir fondo, inicializar, EM, seleccionar reinicio, validar.", "Order: split train/test, choose background, initialize, EM, select restart, validate.", "Ordén: opdel train/test, vælg baggrund, initialisér, EM, vælg genstart, validér."), (("Test permanece retenido.", "Test remains held out.", "Test forbliver hold-out."),), ("Separar train/test → elegir fondo en train → inicializar múltiples veces → ejecutar EM → seleccionar con criterio de train/validación → evaluar una vez en test y evidencia externa.", "Split train/test → choose background on train → initialize multiple times → run EM → select by train/validation criterion → evaluate once on test and external evidence.", "Opdel train/test → vælg baggrund på train → initialisér flere gange → kør EM → vælg med train/valideringskriterium → evaluér én gang på test og ekstern evidens."), ("Evita ajustar anchura o fondo sobre test.", "Avoid fitting width or background on test.", "Undgå at tilpasse bredde eller baggrund på test."), ""),
    ),
    mcqs=(
        ("001", ("¿Qué suma cada columna PWM?", "What does each PWM column sum to?", "Hvad summerer hver PWM-kolonne til?"), (("one", ("1", "1", "1")), ("zero", ("0", "0", "0")), ("width", ("Anchura", "Width", "Bredde"))), "one", ("Cada columna es una distribución.", "Each column is a distribution.", "Hver kolonne er en fordeling.")),
        ("002", ("¿Qué evita un pseudoconteo?", "What does a pseudocount avoid?", "Hvad undgår en pseudotælling?"), (("zero", ("Probabilidades cero accidentales", "Accidental zero probabilities", "Utilsigtede nulsandsynligheder")), ("sites", ("Todos los sitios", "All sites", "Alle sites")), ("logs", ("Cualquier logaritmo", "Any logarithm", "Enhver logaritme"))), "zero", ("Regulariza conteos escasos.", "It regularizes sparse counts.", "Den regulariserer sparsomme tællinger.")),
        ("003", ("¿Cuándo es máxima la entropía ADN?", "When is DNA entropy maximal?", "Hvornår er DNA-entropi maksimal?"), (("uniform", ("Bases equiprobables", "Equiprobable bases", "Lige sandsynlige baser")), ("one", ("Una base domina", "One base dominates", "Én base dominerer")), ("zero", ("Sin bases", "No bases", "Ingen baser"))), "uniform", ("La incertidumbre es máxima.", "Uncertainty is maximal.", "Usikkerheden er maksimal.")),
        ("004", ("¿Qué asume una PWM estándar?", "What does a standard PWM assume?", "Hvad antager en standard-PWM?"), (("independent", ("Independencia entre posiciones", "Independence across positions", "Uafhængighed mellem positioner")), ("dependent", ("Dependencia arbitraria", "Arbitrary dependence", "Vilkårlig afhængighed")), ("order", ("Orden desconocido", "Unknown order", "Ukendt rækkefølge"))), "independent", ("El score suma términos por posición.", "Score sums terms by position.", "Scoren summerer led pr. position.")),
        ("005", ("¿Qué modelo fuerza un sitio por secuencia?", "Which model forces one site per sequence?", "Hvilken model tvinger ét site pr. sekvens?"), (("oops", ("OOPS", "OOPS", "OOPS")), ("zoops", ("ZOOPS", "ZOOPS", "ZOOPS")), ("tcm", ("TCM", "TCM", "TCM"))), "oops", ("One occurrence per sequence.", "One occurrence per sequence.", "One occurrence per sequence.")),
        ("006", ("¿Qué calcula E-step?", "What does the E-step compute?", "Hvad beregner E-trinnet?"), (("responsibilities", ("Responsabilidades de posiciones", "Position responsibilities", "Ansvar for positioner")), ("final", ("Motivo final garantizado", "Guaranteed final motif", "Garanteret endeligt motiv")), ("width", ("Anchura automática exacta", "Exact automatic width", "Eksakt automatisk bredde"))), "responsibilities", ("Usa parámetros actuales para inferir latentes.", "It uses current parameters to infer latent variables.", "Det bruger aktuelle parametre til at inferere latente variable.")),
        ("007", ("¿Qué actualiza M-step?", "What does the M-step update?", "Hvad opdaterer M-trinnet?"), (("parameters", ("PWM y parámetros", "PWM and parameters", "PWM og parametre")), ("test", ("Datos de test", "Test data", "Testdata")), ("labels", ("Etiquetas conocidas", "Known labels", "Kendte labels"))), "parameters", ("Maximiza expectativa de log-likelihood.", "It maximizes expected log-likelihood.", "Det maksimerer forventet log-likelihood.")),
        ("008", ("¿Qué riesgo tiene EM?", "What risk does EM have?", "Hvilken risiko har EM?"), (("local", ("Óptimos locales", "Local optima", "Lokale optima")), ("decrease", ("Likelihood siempre disminuye", "Likelihood always decreases", "Likelihood falder altid")), ("exact", ("Solución global exacta", "Exact global solution", "Eksakt global løsning"))), "local", ("La inicialización afecta resultado.", "Initialization affects outcome.", "Initialisering påvirker resultatet.")),
        ("009", ("¿Qué valida un motivo fuera de muestra?", "What validates a motif out of sample?", "Hvad validerer et motiv uden for sample?"), (("heldout", ("Enriquecimiento en secuencias retenidas", "Enrichment in held-out sequences", "Berigelse i hold-out-sekvenser")), ("training", ("Sólo likelihood de train", "Training likelihood only", "Kun train-likelihood")), ("logo", ("Logo atractivo", "Attractive logo", "Flot logo"))), "heldout", ("Evalúa generalización.", "It evaluates generalization.", "Det evaluerer generalisering.")),
        ("010", ("¿Qué puede producir fondo incorrecto?", "What can a wrong background produce?", "Hvad kan en forkert baggrund producere?"), (("composition", ("Motivos de composición", "Composition motifs", "Sammensætningsmotiver")), ("truth", ("Verdad garantizada", "Guaranteed truth", "Garanteret sandhed")), ("none", ("Ningún efecto", "No effect", "Ingen effekt"))), "composition", ("El modelo confunde GC u otras dependencias con señal.", "The model confuses GC or other dependencies with signal.", "Modellen forveksler GC eller andre afhængigheder med signal.")),
    ),
    true_false=(
        ("011", ("Una PWM puede estimarse sin pseudoconteos cuando hay pocos sitios sin riesgo.", "A PWM can be estimated without pseudocounts from few sites without risk.", "En PWM kan estimeres uden pseudotællinger fra få sites uden risiko."), False, ("Aparecen ceros y sobreajuste.", "Zeros and overfitting appear.", "Nuller og overfitting opstår.")),
        ("012", ("Entropía baja indica conservación alta.", "Low entropy indicates high conservation.", "Lav entropi indikerer høj konservering."), True, ("Una base domina la distribución.", "One base dominates the distribution.", "Én base dominerer fordelingen.")),
        ("013", ("El score PWM depende del fondo.", "PWM score depends on background.", "PWM-score afhænger af baggrunden."), True, ("Es una razón de probabilidades.", "It is a probability ratio.", "Det er et sandsynlighedsforhold.")),
        ("014", ("OOPS permite cero sitios.", "OOPS allows zero sites.", "OOPS tillader nul sites."), False, ("OOPS fuerza uno.", "OOPS forces one.", "OOPS tvinger ét.")),
        ("015", ("ZOOPS permite cero o un sitio.", "ZOOPS allows zero or one site.", "ZOOPS tillader nul eller ét site."), True, ("Es su definición.", "That is its definition.", "Det er definitionen.")),
        ("016", ("EM garantiza el óptimo global.", "EM guarantees the global optimum.", "EM garanterer det globale optimum."), False, ("Puede converger a óptimos locales.", "It may converge to local optima.", "Det kan konvergere til lokale optima.")),
        ("017", ("Múltiples reinicios ayudan a evaluar estabilidad.", "Multiple restarts help assess stability.", "Flere genstarter hjælper med at vurdere stabilitet."), True, ("Revelan soluciones alternativas.", "They reveal alternative solutions.", "De afslører alternative løsninger.")),
        ("018", ("La mejor likelihood de train garantiza el mejor motivo biológico.", "Best training likelihood guarantees the best biological motif.", "Bedste train-likelihood garanterer det bedste biologiske motiv."), False, ("Puede sobreajustar o captar composición.", "It may overfit or capture composition.", "Den kan overfitte eller fange sammensætning.")),
        ("019", ("Un logo de secuencia demuestra unión funcional.", "A sequence logo proves functional binding.", "Et sekvenslogo beviser funktionel binding."), False, ("Es una visualización descriptiva.", "It is a descriptive visualization.", "Det er en deskriptiv visualisering.")),
        ("020", ("La validación externa fortalece interpretación.", "External validation strengthens interpretation.", "Ekstern validering styrker fortolkningen."), True, ("ChIP, conservación u otros datos aportan evidencia independiente.", "ChIP, conservation, or other data provide independent evidence.", "ChIP, konservering eller andre data giver uafhængig evidens.")),
    ),
    tutor=(
        ("El descubrimiento de motivos representa sitios mediante PWM regularizadas con pseudoconteos. Entropía e información cuantifican conservación, pero un logo no demuestra función. Los scores log-odds comparan PWM con un fondo cuya composición debe corresponder a los datos. OOPS, ZOOPS y TCM expresan diferentes supuestos de ocurrencia. EM alterna responsabilidades de posiciones latentes y actualización de parámetros; aumenta likelihood localmente, pero depende de inicialización, anchura y fondo. Múltiples reinicios, datos retenidos, controles de composición y evidencia externa son esenciales para distinguir señal reproducible de artefactos de baja complejidad.", "Motif discovery represents sites with PWMs regularized by pseudocounts. Entropy and information quantify conservation, but a logo does not prove function. Log-odds scores compare a PWM with a background whose composition should match the data. OOPS, ZOOPS, and TCM express different occurrence assumptions. EM alternates latent-position responsibilities and parameter updates; it increases likelihood locally but depends on initialization, width, and background. Multiple restarts, held-out data, composition controls, and external evidence are essential to distinguish reproducible signal from low-complexity artifacts.", "Motivopdagelse repræsenterer sites med PWM'er regulariseret af pseudotællinger. Entropi og information kvantificerer konservering, men et logo beviser ikke funktion. Log-odds-scores sammenligner en PWM med en baggrund, hvis sammensætning bør passe til data. OOPS, ZOOPS og TCM udtrykker forskellige antagelser om forekomst. EM skifter mellem ansvar for latente positioner og parameteropdatering; det øger likelihood lokalt, men afhænger af initialisering, bredde og baggrund. Flere genstarter, hold-out-data, sammensætningskontroller og ekstern evidens er essentielle for at skelne reproducerbart signal fra artefakter med lav kompleksitet."),
        (("PWM'er kræver pseudotællinger.", "PWMs require pseudocounts.", "PWM'er kræver pseudotællinger."), ("Entropi måler usikkerhed.", "Entropy measures uncertainty.", "Entropi måler usikkerhed."), ("Score afhænger af baggrund.", "Score depends on background.", "Score afhænger af baggrund."), ("Forekomstmodellen er en antagelse.", "Occurrence model is an assumption.", "Forekomstmodellen er en antagelse."), ("EM finder lokale optima.", "EM finds local optima.", "EM finder lokale optima."), ("Validering kræver hold-out og ekstern evidens.", "Validation requires held-out and external evidence.", "Validering kræver hold-out og ekstern evidens.")),
        (("Udelade pseudotællinger.", "Omitting pseudocounts.", "Udelade pseudotællinger."), ("Antage uniform baggrund.", "Assuming uniform background.", "Antage uniform baggrund."), ("Tvinge OOPS ved fraværende sites.", "Forcing OOPS when sites may be absent.", "Tvinge OOPS når sites kan mangle."), ("Bruge én EM-initialisering.", "Using one EM initialization.", "Bruge én EM-initialisering."), ("Vælge bredde på testdata.", "Selecting width on test data.", "Vælge bredde på testdata."), ("Fortolke logo som funktionelt bevis.", "Interpreting a logo as functional proof.", "Fortolke logo som funktionelt bevis.")),
        (("Hvilken baggrund bruges?", "Which background is used?", "Hvilken baggrund bruges?"), ("Hvilken forekomstmodel er passende?", "Which occurrence model is appropriate?", "Hvilken forekomstmodel er passende?"), ("Hvordan vælges bredde?", "How is width selected?", "Hvordan vælges bredde?"), ("Hvor mange genstarter?", "How many restarts?", "Hvor mange genstarter?"), ("Er motivet stabilt?", "Is the motif stable?", "Er motivet stabilt?"), ("Hvilken ekstern evidens findes?", "What external evidence exists?", "Hvilken ekstern evidens findes?")),
        (("Bygger og normaliserer PWM.", "Builds and normalizes PWM.", "Bygger og normaliserer PWM."), ("Fortolker entropi og information.", "Interprets entropy and information.", "Fortolker entropi og information."), ("Formulerer log-odds mod korrekt baggrund.", "Formulates log-odds against correct background.", "Formulerer log-odds mod korrekt baggrund."), ("Forklarer E/M-trin.", "Explains E/M steps.", "Forklarer E/M-trin."), ("Håndterer lokale optima.", "Handles local optima.", "Håndterer lokale optima."), ("Designer uafhængig validering.", "Designs independent validation.", "Designer uafhængig validering.")),
        (("Opfind ikke bindingssteder.", "Do not invent binding sites.", "Opfind ikke bindingssteder."), ("Hævd ikke funktion fra PWM alene.", "Do not claim function from PWM alone.", "Hævd ikke funktion fra PWM alene."), ("Skjul ikke baggrund eller pseudotællinger.", "Do not hide background or pseudocounts.", "Skjul ikke baggrund eller pseudotællinger."), ("Brug ikke undervisningsmotiver klinisk.", "Do not use teaching motifs clinically.", "Brug ikke undervisningsmotiver klinisk."), ("Svar på aktivt sprog.", "Answer in active language.", "Svar på aktivt sprog.")),
        ("MEME and probabilistic motif-discovery literature.", "Shannon entropy and sequence-logo foundations.", "Expectation-maximization derivations for OOPS and ZOOPS.", "Background Markov models for regulatory sequence.", "Motif enrichment and held-out validation principles.", "Active SDU DM847 de novo motif learning outcomes."),
    ),
)

LOCALIZED_MODULE_08_MOTIF_DISCOVERY_EM: LocalizedLearningModule = build_module(_SPEC)
LOCALIZED_OBJECTIVE_QUESTION_BANK_08 = build_question_bank(_SPEC)


def materialize_module_08_question_bank(locale: AppLocale | str = AppLocale.SPANISH_SPAIN) -> tuple[AssessmentItem, ...]:
    return materialize_bank(LOCALIZED_OBJECTIVE_QUESTION_BANK_08, locale)


MODULE_08_MOTIF_DISCOVERY_EM: LearningModule = LOCALIZED_MODULE_08_MOTIF_DISCOVERY_EM.materialize(AppLocale.SPANISH_SPAIN)
OBJECTIVE_QUESTION_BANK_08 = materialize_module_08_question_bank()

__all__ = ["LOCALIZED_MODULE_08_MOTIF_DISCOVERY_EM", "LOCALIZED_OBJECTIVE_QUESTION_BANK_08", "MODULE_08_MOTIF_DISCOVERY_EM", "OBJECTIVE_QUESTION_BANK_08", "materialize_module_08_question_bank"]
