"""BMB831 module 1: scalable relational workflows with Synthea data."""

from __future__ import annotations

from ...i18n import AppLocale
from ..models import AssessmentItem, LearningModule
from .authoring import Triple
from .standard import (
    McqSpec,
    OptionSpec,
    StandardModuleSpec,
    TfSpec,
    build_module,
    build_question_bank,
    materialize_bank,
)


def _t(spanish: str, english: str, danish: str) -> Triple:
    return spanish, english, danish


def _option(option_id: str, text: Triple) -> OptionSpec:
    return option_id, text


def _mcq(
    item_id: str,
    prompt: Triple,
    options: tuple[OptionSpec, ...],
    correct_option_id: str,
    explanation: Triple,
) -> McqSpec:
    return item_id, prompt, options, correct_option_id, explanation


def _tf(item_id: str, prompt: Triple, correct: bool, explanation: Triple) -> TfSpec:
    return item_id, prompt, correct, explanation


_SPEC = StandardModuleSpec(
    module_id="bmb831.m01",
    title=_t(
        "Flujos reproducibles con datos clínicos de Synthea",
        "Reproducible workflows with Synthea clinical data",
        "Reproducerbare workflows med kliniske Synthea-data",
    ),
    summary=_t(
        "Construye tablas analíticas trazables a partir de archivos clínicos relacionales, valida claves y cardinalidades, preserva la unidad paciente y distingue datos sintéticos de evidencia clínica u ómica real.",
        "Build traceable analytical tables from relational clinical files, validate keys and cardinalities, preserve the patient as the independent unit, and distinguish synthetic data from real clinical or omics evidence.",
        "Byg sporbare analysetabeller fra relationelle kliniske filer, validér nøgler og kardinaliteter, bevar patienten som uafhængig enhed, og skeln syntetiske data fra reel klinisk eller omisk evidens.",
    ),
    objectives=(
        (
            "m01.o1",
            _t(
                "Explicar la procedencia, utilidad y límites de los datos generados por Synthea.",
                "Explain the provenance, utility, and limitations of data generated by Synthea.",
                "Forklare proveniens, nytte og begrænsninger ved data genereret af Synthea.",
            ),
        ),
        (
            "m01.o2",
            _t(
                "Validar claves primarias, claves foráneas, granularidad y cardinalidad antes de unir tablas.",
                "Validate primary keys, foreign keys, grain, and cardinality before joining tables.",
                "Validere primærnøgler, fremmednøgler, granularitet og kardinalitet før tabeller joines.",
            ),
        ),
        (
            "m01.o3",
            _t(
                "Transformar eventos longitudinales en características a nivel de paciente sin pseudorreplicación ni fuga temporal.",
                "Transform longitudinal events into patient-level features without pseudoreplication or temporal leakage.",
                "Transformere longitudinelle hændelser til patientniveau-features uden pseudoreplikation eller tidsmæssig leakage.",
            ),
        ),
        (
            "m01.o4",
            _t(
                "Diseñar un flujo de R reproducible y escalable con manifiesto, validaciones y resultados auditables.",
                "Design a reproducible and scalable R workflow with a manifest, validations, and auditable outputs.",
                "Designe et reproducerbart og skalerbart R-workflow med manifest, valideringer og auditerbare outputs.",
            ),
        ),
    ),
    concepts=(
        (
            "synthea-boundary",
            _t(
                "Procedencia y límite de Synthea",
                "Synthea provenance and boundary",
                "Synthea-proveniens og afgrænsning",
            ),
            _t(
                "Synthea genera historias clínicas sintéticas mediante simulación basada en agentes y módulos de enfermedad. Sus archivos permiten practicar ingeniería de datos, modelos longitudinales, validación y visualización sin exponer pacientes reales. Sin embargo, no son observaciones clínicas reales, no validan utilidad clínica y no sustituyen datos ómicos para aprender pipelines de transcriptómica o proteómica.",
                "Synthea generates synthetic health records through agent-based simulation and disease modules. Its files support practice in data engineering, longitudinal modeling, validation, and visualization without exposing real patients. However, they are not real clinical observations, do not establish clinical utility, and do not replace omics data for learning transcriptomics or proteomics pipelines.",
                "Synthea genererer syntetiske patientjournaler gennem agentbaseret simulering og sygdomsmoduler. Filerne understøtter træning i data engineering, longitudinel modellering, validering og visualisering uden virkelige patienter. De er dog ikke reelle kliniske observationer, dokumenterer ikke klinisk nytte og erstatter ikke omikdata til læring af transkriptomik- eller proteomik-pipelines.",
            ),
            (
                _t(
                    "Synthetic no significa observado ni clínicamente validado.",
                    "Synthetic does not mean observed or clinically validated.",
                    "Syntetisk betyder ikke observeret eller klinisk valideret.",
                ),
                _t(
                    "El generador, la versión, la semilla y la configuración forman parte de la procedencia.",
                    "The generator, version, seed, and configuration are part of provenance.",
                    "Generator, version, seed og konfiguration er en del af proveniensen.",
                ),
            ),
        ),
        (
            "relational-contract",
            _t(
                "Contrato relacional y granularidad",
                "Relational contract and grain",
                "Relationel kontrakt og granularitet",
            ),
            _t(
                "patients.csv contiene una fila por paciente, mientras encounters.csv, conditions.csv u observations.csv pueden contener muchas filas por paciente. Antes de un join se declara qué representa una fila, se comprueba unicidad de la clave primaria, cobertura de claves foráneas y cardinalidad esperada. Un join sintácticamente correcto puede multiplicar filas y alterar denominadores si la granularidad no se controla.",
                "patients.csv contains one row per patient, whereas encounters.csv, conditions.csv, or observations.csv may contain many rows per patient. Before a join, state what one row represents and verify primary-key uniqueness, foreign-key coverage, and expected cardinality. A syntactically valid join can multiply rows and change denominators when grain is uncontrolled.",
                "patients.csv indeholder én række pr. patient, mens encounters.csv, conditions.csv eller observations.csv kan indeholde mange rækker pr. patient. Før et join angives, hvad én række repræsenterer, og primærnøglens unikhed, fremmednøgledækning og forventet kardinalitet kontrolleres. Et syntaktisk gyldigt join kan multiplicere rækker og ændre nævnere, hvis granulariteten ikke kontrolleres.",
            ),
            (
                _t(
                    "Cuenta filas y claves únicas antes y después del join.",
                    "Count rows and unique keys before and after the join.",
                    "Tæl rækker og unikke nøgler før og efter joinet.",
                ),
                _t(
                    "No unas dos tablas de eventos directamente sin definir el producto esperado.",
                    "Do not join two event tables directly without defining the expected product.",
                    "Join ikke to hændelsestabeller direkte uden at definere det forventede produkt.",
                ),
            ),
        ),
        (
            "longitudinal-unit",
            _t(
                "Unidad independiente y tiempo",
                "Independent unit and time",
                "Uafhængig enhed og tid",
            ),
            _t(
                "Las visitas, diagnósticos y observaciones repetidas pertenecen al mismo paciente y no son réplicas independientes. Para un análisis transversal se agregan eventos dentro de una ventana definida; para predicción se fija un tiempo índice y sólo se usan datos disponibles antes de ese punto. El split de entrenamiento y prueba debe mantener todos los registros de un paciente en el mismo conjunto.",
                "Repeated visits, diagnoses, and observations belong to the same patient and are not independent replicates. For a cross-sectional analysis, aggregate events within a declared window; for prediction, define an index time and use only data available before it. Training and test splits must keep all records from one patient in the same set.",
                "Gentagne besøg, diagnoser og observationer tilhører samme patient og er ikke uafhængige replikater. Til en tværsnitsanalyse aggregeres hændelser inden for et deklareret vindue; til prædiktion defineres et indekstidspunkt, og kun tidligere data anvendes. Trænings- og testsplit skal holde alle poster fra samme patient i samme sæt.",
            ),
            (
                _t(
                    "Paciente, no encuentro, suele ser la unidad de split.",
                    "The patient, not the encounter, is usually the splitting unit.",
                    "Patienten, ikke encounteret, er normalt split-enheden.",
                ),
                _t(
                    "Una variable posterior al outcome produce fuga temporal.",
                    "A variable recorded after the outcome creates temporal leakage.",
                    "En variabel registreret efter outcome skaber tidsmæssig leakage.",
                ),
            ),
        ),
        (
            "scalable-workflow",
            _t(
                "Flujo escalable y auditable",
                "Scalable and auditable workflow",
                "Skalerbart og auditerbart workflow",
            ),
            _t(
                "Un flujo reproducible conserva un manifiesto del dataset, lee sólo columnas necesarias, valida el esquema, reduce eventos a la granularidad analítica, registra dimensiones intermedias y escribe resultados derivados sin modificar los archivos fuente. Para mayor escala se evita copiar objetos innecesariamente, se filtra temprano y se mide memoria y tiempo antes de optimizar.",
                "A reproducible workflow retains a dataset manifest, reads only required columns, validates the schema, reduces events to the analytical grain, records intermediate dimensions, and writes derived outputs without modifying source files. At larger scale, avoid unnecessary copies, filter early, and measure memory and runtime before optimizing.",
                "Et reproducerbart workflow bevarer et datasetmanifest, læser kun nødvendige kolonner, validerer skemaet, reducerer hændelser til den analytiske granularitet, registrerer mellemliggende dimensioner og skriver afledte outputs uden at ændre kildefiler. Ved større skala undgås unødvendige kopier, der filtreres tidligt, og hukommelse samt køretid måles før optimering.",
            ),
            (
                _t(
                    "Los archivos fuente son inmutables; las transformaciones producen artefactos derivados.",
                    "Source files are immutable; transformations produce derived artifacts.",
                    "Kildefiler er uforanderlige; transformationer producerer afledte artefakter.",
                ),
                _t(
                    "Una dimensión inesperada debe detener el análisis, no quedar oculta.",
                    "An unexpected dimension should stop the analysis rather than remain hidden.",
                    "En uventet dimension bør stoppe analysen frem for at forblive skjult.",
                ),
            ),
        ),
    ),
    examples=(
        (
            "m01.e01",
            _t(
                "Validar una relación paciente–encuentro",
                "Validate a patient–encounter relation",
                "Validér en patient–encounter-relation",
            ),
            _t(
                "Comprueba claves, cobertura y conteos antes de construir una tabla unida con estructura equivalente a las tablas CSV de Synthea.",
                "Check keys, coverage, and counts before constructing a joined table with a structure equivalent to Synthea CSV tables.",
                "Kontrollér nøgler, dækning og antal før opbygning af en joinet tabel med en struktur svarende til Synthea-CSV-tabeller.",
            ),
            (
                _t(
                    "patients tiene una fila por paciente.",
                    "patients has one row per patient.",
                    "patients har én række pr. patient.",
                ),
                _t(
                    "encounters puede contener cero o más filas por paciente.",
                    "encounters may contain zero or more rows per patient.",
                    "encounters kan indeholde nul eller flere rækker pr. patient.",
                ),
                _t(
                    "La cobertura de la clave foránea se comprueba antes de merge.",
                    "Foreign-key coverage is checked before merge.",
                    "Fremmednøgledækning kontrolleres før merge.",
                ),
            ),
            """patients <- data.frame(
  patient = c("P01", "P02", "P03", "P04"),
  birthdate = as.Date(c("1980-01-01", "1975-06-10", "1992-03-20", "1968-11-05")),
  sex = factor(c("F", "M", "F", "M"))
)
encounters <- data.frame(
  encounter_id = paste0("E0", 1:6),
  patient = c("P01", "P01", "P02", "P04", "P04", "P04"),
  start = as.Date(c("2025-01-03", "2025-02-04", "2025-01-11", "2025-01-20", "2025-02-20", "2025-03-20"))
)
stopifnot(!anyDuplicated(patients$patient))
stopifnot(!anyDuplicated(encounters$encounter_id))
stopifnot(all(encounters$patient %in% patients$patient))
joined <- merge(encounters, patients, by = "patient", all.x = TRUE, sort = FALSE)
cat(sprintf("patients=%d encounters=%d joined=%d\n", nrow(patients), nrow(encounters), nrow(joined)))
counts <- table(factor(encounters$patient, levels = patients$patient))
cat(paste(sprintf("%s=%d", names(counts), as.integer(counts)), collapse = ","))
""",
            """patients=4 encounters=6 joined=6
P01=2,P02=1,P03=0,P04=3""",
            _t(
                "El join conserva seis encuentros y el conteo incluye explícitamente al paciente sin encuentros.",
                "The join retains six encounters and the count explicitly includes the patient without encounters.",
                "Joinet bevarer seks encounters, og optællingen inkluderer eksplicit patienten uden encounters.",
            ),
        ),
        (
            "m01.e02",
            _t(
                "Crear características a nivel de paciente",
                "Create patient-level features",
                "Opret features på patientniveau",
            ),
            _t(
                "Resume observaciones repetidas sin tratarlas como pacientes independientes.",
                "Summarize repeated observations without treating them as independent patients.",
                "Opsummér gentagne observationer uden at behandle dem som uafhængige patienter.",
            ),
            (
                _t(
                    "Primero se filtra el código de interés.",
                    "First filter the code of interest.",
                    "Filtrér først den relevante kode.",
                ),
                _t(
                    "Después se calcula una fila de características por paciente.",
                    "Then compute one feature row per patient.",
                    "Beregn derefter én feature-række pr. patient.",
                ),
            ),
            """observations <- data.frame(
  patient = c("P01", "P01", "P02", "P02", "P04", "P04"),
  code = c("BMI", "BMI", "BMI", "BMI", "BMI", "SBP"),
  value = c(22, 24, 31, 29, 27, 135)
)
bmi <- observations[observations$code == "BMI", c("patient", "value")]
bmi_n <- tapply(bmi$value, bmi$patient, length)
bmi_mean <- tapply(bmi$value, bmi$patient, mean)
features <- data.frame(
  patient = names(bmi_mean),
  bmi_n = as.integer(bmi_n[names(bmi_mean)]),
  bmi_mean = as.numeric(bmi_mean)
)
cat(paste(sprintf("%s:n=%d,mean=%.1f", features$patient, features$bmi_n, features$bmi_mean), collapse = "\n"))
""",
            """P01:n=2,mean=23.0
P02:n=2,mean=30.0
P04:n=1,mean=27.0""",
            _t(
                "La tabla final contiene una fila por paciente con número de mediciones y media, manteniendo visible la cantidad de información disponible.",
                "The final table contains one row per patient with measurement count and mean, keeping the amount of available information visible.",
                "Den endelige tabel indeholder én række pr. patient med antal målinger og gennemsnit, så mængden af tilgængelig information forbliver synlig.",
            ),
        ),
    ),
    practices=(
        (
            "m01.p01",
            "DATA_INTERPRETATION",
            _t(
                "Indica la granularidad y la clave esperada de patients, encounters y observations.",
                "State the expected grain and key for patients, encounters, and observations.",
                "Angiv forventet granularitet og nøgle for patients, encounters og observations.",
            ),
            (
                _t(
                    "Pregunta qué representa una fila.",
                    "Ask what one row represents.",
                    "Spørg hvad én række repræsenterer.",
                ),
            ),
            _t(
                "patients: una fila por ID de paciente; encounters: una fila por ID de encuentro; observations: una fila por evento de observación enlazado a paciente y normalmente a encuentro.",
                "patients: one row per patient ID; encounters: one row per encounter ID; observations: one row per observation event linked to a patient and usually an encounter.",
                "patients: én række pr. patient-ID; encounters: én række pr. encounter-ID; observations: én række pr. observationshændelse knyttet til en patient og normalt et encounter.",
            ),
            _t(
                "La granularidad determina las claves y los joins válidos.",
                "Grain determines valid keys and joins.",
                "Granularitet bestemmer gyldige nøgler og joins.",
            ),
            "",
        ),
        (
            "m01.p02",
            "DEBUGGING",
            _t(
                "Dos tablas de eventos contienen tres diagnósticos y cuatro medicaciones para el mismo paciente. Explica por qué unirlas sólo por patient produce doce filas.",
                "Two event tables contain three diagnoses and four medications for the same patient. Explain why joining them only by patient produces twelve rows.",
                "To hændelsestabeller indeholder tre diagnoser og fire mediciner for samme patient. Forklar hvorfor et join kun på patient giver tolv rækker.",
            ),
            (
                _t(
                    "Es un producto muchos-a-muchos.",
                    "It is a many-to-many product.",
                    "Det er et mange-til-mange-produkt.",
                ),
            ),
            _t(
                "Cada diagnóstico se combina con cada medicación. Agrega primero a nivel de paciente o define una relación temporal y una clave más específica.",
                "Each diagnosis is paired with every medication. Aggregate to patient level first or define a temporal relation and a more specific key.",
                "Hver diagnose kombineres med hver medicin. Aggregér først til patientniveau eller definér en tidsrelation og en mere specifik nøgle.",
            ),
            _t(
                "Un join muchos-a-muchos no es necesariamente incorrecto, pero debe ser intencional y verificable.",
                "A many-to-many join is not necessarily wrong, but it must be intentional and verifiable.",
                "Et mange-til-mange-join er ikke nødvendigvis forkert, men det skal være tilsigtet og verificerbart.",
            ),
            "",
        ),
        (
            "m01.p03",
            "CODE_COMPLETION",
            _t(
                "Completa las validaciones para una tabla patients con clave ID y una tabla encounters con clave PATIENT.",
                "Complete the validations for a patients table keyed by ID and an encounters table keyed by PATIENT.",
                "Fuldfør valideringerne for en patients-tabel med nøglen ID og en encounters-tabel med nøglen PATIENT.",
            ),
            (
                _t(
                    "Comprueba unicidad y cobertura.",
                    "Check uniqueness and coverage.",
                    "Kontrollér unikhed og dækning.",
                ),
            ),
            _t(
                "stopifnot(!anyDuplicated(patients$ID)); stopifnot(all(encounters$PATIENT %in% patients$ID))",
                "stopifnot(!anyDuplicated(patients$ID)); stopifnot(all(encounters$PATIENT %in% patients$ID))",
                "stopifnot(!anyDuplicated(patients$ID)); stopifnot(all(encounters$PATIENT %in% patients$ID))",
            ),
            _t(
                "Las dos aserciones detectan pacientes duplicados y encuentros huérfanos antes del análisis.",
                "The two assertions detect duplicate patients and orphan encounters before analysis.",
                "De to assertions opdager dublerede patienter og forældreløse encounters før analysen.",
            ),
            "stopifnot(__________________)\nstopifnot(__________________)",
        ),
        (
            "m01.p04",
            "PIPELINE_DESIGN",
            _t(
                "Diseña un flujo desde un snapshot CSV de Synthea hasta una tabla analítica de una fila por paciente.",
                "Design a workflow from a Synthea CSV snapshot to an analytical table with one row per patient.",
                "Design et workflow fra et Synthea-CSV-snapshot til en analysetabel med én række pr. patient.",
            ),
            (
                _t(
                    "Incluye manifiesto, validación, ventanas temporales y artefactos derivados.",
                    "Include a manifest, validation, time windows, and derived artifacts.",
                    "Medtag manifest, validering, tidsvinduer og afledte artefakter.",
                ),
            ),
            _t(
                "Registrar versión/semilla/checksums → leer columnas necesarias → validar esquema y claves → definir cohorte y tiempo índice → filtrar eventos previos → agregar por paciente → unir características → comprobar una fila por paciente → guardar tabla derivada y registro de decisiones.",
                "Record version/seed/checksums → read required columns → validate schema and keys → define cohort and index time → filter prior events → aggregate by patient → join features → verify one row per patient → save the derived table and decision log.",
                "Registrér version/seed/checksums → læs nødvendige kolonner → validér skema og nøgler → definér kohorte og indekstid → filtrér tidligere hændelser → aggregér pr. patient → join features → verificér én række pr. patient → gem afledt tabel og beslutningslog.",
            ),
            _t(
                "El flujo separa datos fuente, reglas analíticas y resultados derivados.",
                "The workflow separates source data, analytical rules, and derived results.",
                "Workflowet adskiller kildedata, analytiske regler og afledte resultater.",
            ),
            "",
        ),
        (
            "m01.p05",
            "ORAL_EXPLANATION",
            _t(
                "Prepara un esquema de 90 segundos para explicar por qué seis encuentros del mismo paciente no equivalen a seis pacientes. No se requiere audio: escribe tesis, dos razones y una consecuencia analítica.",
                "Prepare a 90-second outline explaining why six encounters from one patient do not equal six patients. No audio is required: write a thesis, two reasons, and one analytical consequence.",
                "Forbered en 90-sekunders disposition, der forklarer hvorfor seks encounters fra én patient ikke svarer til seks patienter. Lyd er ikke påkrævet: skriv tese, to grunde og én analytisk konsekvens.",
            ),
            (
                _t(
                    "Menciona dependencia y error estándar.",
                    "Mention dependence and standard error.",
                    "Nævn afhængighed og standardfejl.",
                ),
            ),
            _t(
                "Tesis: la unidad independiente es el paciente. Razones: los encuentros comparten biología e historia y sus errores están correlacionados. Consecuencia: tratarlos como independientes infla n, estrecha intervalos y puede sesgar validación; se debe agregar, modelar la dependencia o dividir por paciente.",
                "Thesis: the independent unit is the patient. Reasons: encounters share biology and history, and their errors are correlated. Consequence: treating them as independent inflates n, narrows intervals, and can bias validation; aggregate, model dependence, or split by patient.",
                "Tese: den uafhængige enhed er patienten. Grunde: encounters deler biologi og historik, og deres fejl er korrelerede. Konsekvens: behandling som uafhængige inflaterer n, indsnævrer intervaller og kan skævvride validering; aggregér, modellér afhængighed eller split efter patient.",
            ),
            _t(
                "El formato escrito entrena la estructura lógica que después puede verbalizarse sin depender de reconocimiento de voz.",
                "The written format trains the logical structure that can later be spoken without relying on speech recognition.",
                "Det skriftlige format træner den logiske struktur, som senere kan fremsiges uden talegenkendelse.",
            ),
            "",
        ),
        (
            "m01.p06",
            "SHORT_ANSWER",
            _t(
                "Evalúa la afirmación: 'Un modelo funciona bien en Synthea, por tanto está validado para pacientes reales'.",
                "Evaluate the claim: 'A model works well on Synthea, therefore it is validated for real patients.'",
                "Vurdér påstanden: 'En model virker godt på Synthea og er derfor valideret til virkelige patienter.'",
            ),
            (
                _t(
                    "Separa validación técnica de validación clínica.",
                    "Separate technical validation from clinical validation.",
                    "Adskil teknisk validering fra klinisk validering.",
                ),
            ),
            _t(
                "La afirmación es inválida. Synthea permite comprobar código, contratos, leakage y comportamiento bajo escenarios simulados, pero el rendimiento depende del generador. Se requiere validación externa con datos reales representativos y evaluación clínica del uso previsto.",
                "The claim is invalid. Synthea can test code, contracts, leakage, and behavior under simulated scenarios, but performance depends on the generator. External validation on representative real data and clinical evaluation for the intended use are required.",
                "Påstanden er ugyldig. Synthea kan teste kode, kontrakter, leakage og adfærd under simulerede scenarier, men præstation afhænger af generatoren. Ekstern validering på repræsentative reelle data og klinisk vurdering til det tilsigtede formål er nødvendig.",
            ),
            _t(
                "La utilidad pedagógica de datos sintéticos no debe convertirse en una afirmación de eficacia clínica.",
                "The pedagogical utility of synthetic data must not become a claim of clinical effectiveness.",
                "Den pædagogiske nytte af syntetiske data må ikke blive til en påstand om klinisk effekt.",
            ),
            "",
        ),
    ),
    mcqs=(
        _mcq(
            "q01",
            _t(
                "¿Cuál es la unidad independiente más defendible al predecir un outcome por persona?",
                "What is the most defensible independent unit when predicting a person-level outcome?",
                "Hvad er den mest forsvarlige uafhængige enhed ved prædiktion af et outcome på personniveau?",
            ),
            (
                _option("a", _t("Cada observación", "Each observation", "Hver observation")),
                _option("b", _t("Cada encuentro", "Each encounter", "Hvert encounter")),
                _option("c", _t("Cada paciente", "Each patient", "Hver patient")),
                _option("d", _t("Cada código clínico", "Each clinical code", "Hver klinisk kode")),
            ),
            "c",
            _t(
                "Todos los registros de un paciente comparten una unidad biológica y deben permanecer juntos durante la validación.",
                "All records from one patient share a biological unit and should remain together during validation.",
                "Alle poster fra én patient deler en biologisk enhed og bør forblive sammen under validering.",
            ),
        ),
        _mcq(
            "q02",
            _t(
                "¿Qué validación debe ejecutarse antes de unir encounters con patients?",
                "Which validation should run before joining encounters to patients?",
                "Hvilken validering bør køres før encounters joines med patients?",
            ),
            (
                _option(
                    "a",
                    _t(
                        "Comprobar que cada PATIENT existe en patients.ID",
                        "Check that every PATIENT exists in patients.ID",
                        "Kontrollér at hver PATIENT findes i patients.ID",
                    ),
                ),
                _option("b", _t("Ordenar por nombre", "Sort by name", "Sortér efter navn")),
                _option(
                    "c",
                    _t(
                        "Eliminar pacientes sin encuentros",
                        "Delete patients without encounters",
                        "Slet patienter uden encounters",
                    ),
                ),
                _option(
                    "d",
                    _t(
                        "Convertir todos los campos a texto",
                        "Convert every field to text",
                        "Konvertér alle felter til tekst",
                    ),
                ),
            ),
            "a",
            _t(
                "La cobertura de la clave foránea evita encuentros huérfanos y NA inesperados tras el join.",
                "Foreign-key coverage prevents orphan encounters and unexpected NA values after the join.",
                "Fremmednøgledækning forhindrer forældreløse encounters og uventede NA-værdier efter joinet.",
            ),
        ),
        _mcq(
            "q03",
            _t(
                "¿Qué ocurre al unir dos tablas de eventos muchos-a-muchos sólo por patient?",
                "What happens when two many-event tables are joined only by patient?",
                "Hvad sker der når to tabeller med mange hændelser joines kun på patient?",
            ),
            (
                _option(
                    "a",
                    _t(
                        "Se conserva una fila por paciente",
                        "One row per patient is preserved",
                        "Én række pr. patient bevares",
                    ),
                ),
                _option(
                    "b",
                    _t(
                        "Puede producirse un producto de combinaciones",
                        "A product of combinations can be created",
                        "Et produkt af kombinationer kan opstå",
                    ),
                ),
                _option(
                    "c",
                    _t(
                        "Las filas duplicadas desaparecen",
                        "Duplicate rows disappear",
                        "Dublerede rækker forsvinder",
                    ),
                ),
                _option(
                    "d",
                    _t(
                        "R infiere automáticamente la relación temporal",
                        "R automatically infers the temporal relation",
                        "R udleder automatisk tidsrelationen",
                    ),
                ),
            ),
            "b",
            _t(
                "Cada evento de una tabla puede combinarse con cada evento de la otra para el mismo paciente.",
                "Every event in one table can pair with every event in the other for the same patient.",
                "Hver hændelse i den ene tabel kan kombineres med hver hændelse i den anden for samme patient.",
            ),
        ),
        _mcq(
            "q04",
            _t(
                "¿Qué dato forma parte del manifiesto de una generación de Synthea?",
                "Which item belongs in a manifest for a Synthea generation?",
                "Hvilket element hører til et manifest for en Synthea-generering?",
            ),
            (
                _option(
                    "a",
                    _t(
                        "Versión, semilla y configuración",
                        "Version, seed, and configuration",
                        "Version, seed og konfiguration",
                    ),
                ),
                _option(
                    "b",
                    _t("Sólo el número de filas", "Only the row count", "Kun rækkeantallet"),
                ),
                _option(
                    "c",
                    _t(
                        "Una captura del gráfico final",
                        "A screenshot of the final plot",
                        "Et skærmbillede af det endelige plot",
                    ),
                ),
                _option(
                    "d",
                    _t(
                        "La contraseña del usuario",
                        "The user's password",
                        "Brugerens adgangskode",
                    ),
                ),
            ),
            "a",
            _t(
                "La generación depende del software y de parámetros que deben quedar trazables.",
                "Generation depends on software and parameters that must remain traceable.",
                "Genereringen afhænger af software og parametre, som skal være sporbare.",
            ),
        ),
        _mcq(
            "q05",
            _t(
                "¿Cuál es la mejor estrategia para evitar fuga temporal?",
                "What is the best strategy to avoid temporal leakage?",
                "Hvad er den bedste strategi til at undgå tidsmæssig leakage?",
            ),
            (
                _option(
                    "a",
                    _t(
                        "Usar todos los eventos disponibles",
                        "Use all available events",
                        "Brug alle tilgængelige hændelser",
                    ),
                ),
                _option(
                    "b",
                    _t(
                        "Definir un tiempo índice y usar sólo información previa",
                        "Define an index time and use only prior information",
                        "Definér et indekstidspunkt og brug kun tidligere information",
                    ),
                ),
                _option("c", _t("Eliminar la fecha", "Delete the date", "Slet datoen")),
                _option(
                    "d",
                    _t(
                        "Barajar filas antes de crear variables",
                        "Shuffle rows before creating variables",
                        "Bland rækker før features oprettes",
                    ),
                ),
            ),
            "b",
            _t(
                "La disponibilidad de cada predictor debe evaluarse respecto al tiempo de predicción.",
                "Availability of every predictor must be evaluated relative to prediction time.",
                "Tilgængeligheden af hver prædiktor skal vurderes i forhold til prædiktionstidspunktet.",
            ),
        ),
        _mcq(
            "q06",
            _t(
                "¿Qué conclusión permite un buen rendimiento sobre datos Synthea?",
                "What conclusion is supported by good performance on Synthea data?",
                "Hvilken konklusion understøttes af god præstation på Synthea-data?",
            ),
            (
                _option(
                    "a",
                    _t(
                        "Eficacia clínica demostrada",
                        "Demonstrated clinical effectiveness",
                        "Dokumenteret klinisk effekt",
                    ),
                ),
                _option(
                    "b",
                    _t(
                        "Corrección técnica bajo el escenario simulado",
                        "Technical performance under the simulated scenario",
                        "Teknisk præstation under det simulerede scenarie",
                    ),
                ),
                _option(
                    "c",
                    _t(
                        "Ausencia de sesgo en hospitales reales",
                        "Absence of bias in real hospitals",
                        "Fravær af bias på virkelige hospitaler",
                    ),
                ),
                _option(
                    "d",
                    _t(
                        "Equivalencia con un ensayo clínico",
                        "Equivalence to a clinical trial",
                        "Ækvivalens med et klinisk forsøg",
                    ),
                ),
            ),
            "b",
            _t(
                "El resultado está condicionado por el generador y requiere validación externa para cualquier afirmación clínica.",
                "The result is conditional on the generator and requires external validation for any clinical claim.",
                "Resultatet er betinget af generatoren og kræver ekstern validering for enhver klinisk påstand.",
            ),
        ),
        _mcq(
            "q07",
            _t(
                "¿Qué tabla debe agregarse antes de obtener una fila por paciente?",
                "Which table must be aggregated before obtaining one row per patient?",
                "Hvilken tabel skal aggregeres før der opnås én række pr. patient?",
            ),
            (
                _option(
                    "a",
                    _t(
                        "Una tabla de eventos con múltiples filas por paciente",
                        "An event table with multiple rows per patient",
                        "En hændelsestabel med flere rækker pr. patient",
                    ),
                ),
                _option(
                    "b",
                    _t(
                        "La tabla patients ya única",
                        "The already unique patients table",
                        "Den allerede unikke patients-tabel",
                    ),
                ),
                _option(
                    "c",
                    _t("El manifiesto de datos", "The data manifest", "Datamanifestet"),
                ),
                _option(
                    "d",
                    _t(
                        "La tabla final de resultados",
                        "The final results table",
                        "Den endelige resultattabel",
                    ),
                ),
            ),
            "a",
            _t(
                "Conteos, ventanas y resúmenes transforman eventos repetidos en características al nivel analítico.",
                "Counts, windows, and summaries transform repeated events into features at the analytical level.",
                "Optællinger, vinduer og opsummeringer transformerer gentagne hændelser til features på det analytiske niveau.",
            ),
        ),
        _mcq(
            "q08",
            _t(
                "¿Qué acción favorece un flujo escalable?",
                "Which action supports a scalable workflow?",
                "Hvilken handling understøtter et skalerbart workflow?",
            ),
            (
                _option(
                    "a",
                    _t(
                        "Leer todas las columnas y filtrar al final",
                        "Read every column and filter at the end",
                        "Læs alle kolonner og filtrér til sidst",
                    ),
                ),
                _option(
                    "b",
                    _t(
                        "Filtrar temprano y registrar dimensiones intermedias",
                        "Filter early and record intermediate dimensions",
                        "Filtrér tidligt og registrér mellemliggende dimensioner",
                    ),
                ),
                _option(
                    "c",
                    _t(
                        "Modificar los archivos fuente",
                        "Modify source files",
                        "Ændr kildefilerne",
                    ),
                ),
                _option(
                    "d",
                    _t(
                        "Depender del estado global de R",
                        "Depend on global R state",
                        "Vær afhængig af global R-tilstand",
                    ),
                ),
            ),
            "b",
            _t(
                "Reducir datos temprano y auditar dimensiones limita memoria y detecta errores de cardinalidad.",
                "Reducing data early and auditing dimensions limits memory and detects cardinality errors.",
                "Tidlig datareduktion og audit af dimensioner begrænser hukommelse og opdager kardinalitetsfejl.",
            ),
        ),
    ),
    true_false=(
        _tf(
            "tf01",
            _t(
                "Los registros de Synthea corresponden a pacientes reales anonimizados.",
                "Synthea records are anonymized real patients.",
                "Synthea-poster er anonymiserede virkelige patienter.",
            ),
            False,
            _t(
                "Son historias sintéticas generadas por simulación, no registros reales anonimizados.",
                "They are synthetic histories generated by simulation, not anonymized real records.",
                "De er syntetiske historier genereret ved simulation, ikke anonymiserede reelle journaler.",
            ),
        ),
        _tf(
            "tf02",
            _t(
                "Un join puede ser sintácticamente válido y aun así cambiar incorrectamente el denominador analítico.",
                "A join can be syntactically valid yet still incorrectly change the analytical denominator.",
                "Et join kan være syntaktisk gyldigt og stadig ændre den analytiske nævner forkert.",
            ),
            True,
            _t(
                "La multiplicación de filas por cardinalidad no controlada altera conteos y pesos.",
                "Row multiplication from uncontrolled cardinality changes counts and weights.",
                "Rækkemultiplikation fra ukontrolleret kardinalitet ændrer antal og vægte.",
            ),
        ),
        _tf(
            "tf03",
            _t(
                "Para validación predictiva, encuentros del mismo paciente pueden dividirse libremente entre entrenamiento y prueba.",
                "For predictive validation, encounters from the same patient may be freely split between training and test.",
                "Ved prædiktiv validering kan encounters fra samme patient frit fordeles mellem træning og test.",
            ),
            False,
            _t(
                "La división debe realizarse por paciente para evitar dependencia y fuga de identidad.",
                "Splitting should occur by patient to avoid dependence and identity leakage.",
                "Split bør ske efter patient for at undgå afhængighed og identitets-leakage.",
            ),
        ),
        _tf(
            "tf04",
            _t(
                "La semilla y la configuración de Synthea forman parte de la reproducibilidad.",
                "The Synthea seed and configuration are part of reproducibility.",
                "Synthea-seed og konfiguration er en del af reproducerbarheden.",
            ),
            True,
            _t(
                "Cambiar parámetros puede modificar la población y sus eventos.",
                "Changing parameters can alter the population and its events.",
                "Ændring af parametre kan ændre populationen og dens hændelser.",
            ),
        ),
        _tf(
            "tf05",
            _t(
                "Agregar eventos por paciente siempre elimina toda pérdida de información.",
                "Aggregating events by patient always eliminates all information loss.",
                "Aggregering af hændelser pr. patient eliminerer altid alt informationstab.",
            ),
            False,
            _t(
                "La agregación resume y puede perder tiempo, variabilidad y secuencia; debe responder a la pregunta analítica.",
                "Aggregation summarizes and can lose timing, variability, and sequence; it must match the analytical question.",
                "Aggregering opsummerer og kan miste tid, variation og sekvens; den skal passe til det analytiske spørgsmål.",
            ),
        ),
        _tf(
            "tf06",
            _t(
                "Una variable registrada después del outcome puede causar fuga aunque no contenga el nombre del outcome.",
                "A variable recorded after the outcome can cause leakage even when it does not contain the outcome name.",
                "En variabel registreret efter outcome kan skabe leakage, selv om den ikke indeholder outcome-navnet.",
            ),
            True,
            _t(
                "La fuga depende de disponibilidad temporal, no sólo del nombre de la variable.",
                "Leakage depends on temporal availability, not only on the variable name.",
                "Leakage afhænger af tidsmæssig tilgængelighed, ikke kun af variabelnavnet.",
            ),
        ),
        _tf(
            "tf07",
            _t(
                "Los archivos fuente deberían modificarse para ahorrar espacio durante el análisis.",
                "Source files should be modified to save space during analysis.",
                "Kildefiler bør ændres for at spare plads under analysen.",
            ),
            False,
            _t(
                "Los archivos fuente se conservan inmutables y se generan artefactos derivados trazables.",
                "Source files remain immutable and traceable derived artifacts are produced.",
                "Kildefiler forbliver uforanderlige, og sporbare afledte artefakter produceres.",
            ),
        ),
        _tf(
            "tf08",
            _t(
                "Synthea puede cubrir práctica de ingeniería clínica, pero no satisface por sí sola el resultado de aplicar pipelines ómicos.",
                "Synthea can support clinical data-engineering practice but cannot by itself satisfy the outcome of applying omics pipelines.",
                "Synthea kan understøtte træning i klinisk data engineering, men kan ikke alene opfylde outcome om anvendelse af omik-pipelines.",
            ),
            True,
            _t(
                "Los EHR sintéticos no contienen matrices de expresión o abundancia que sustituyan transcriptómica o proteómica.",
                "Synthetic EHR data do not contain expression or abundance matrices that replace transcriptomics or proteomics.",
                "Syntetiske EHR-data indeholder ikke ekspressions- eller abundansmatricer, der erstatter transkriptomik eller proteomik.",
            ),
        ),
    ),
    tutor=(
        _t(
            "Synthea debe utilizarse como un entorno sintético y reproducible para aprender contratos relacionales, análisis longitudinal y validación técnica. Toda afirmación debe distinguir datos simulados, datos clínicos reales y datos ómicos.",
            "Synthea should be used as a synthetic and reproducible environment for learning relational contracts, longitudinal analysis, and technical validation. Every claim must distinguish simulated data, real clinical data, and omics data.",
            "Synthea bør bruges som et syntetisk og reproducerbart miljø til læring af relationelle kontrakter, longitudinel analyse og teknisk validering. Enhver påstand skal skelne simulerede data, reelle kliniske data og omikdata.",
        ),
        (
            _t(
                "Una fila debe tener una granularidad declarada.",
                "Every row should have a declared grain.",
                "Hver række bør have en deklareret granularitet.",
            ),
            _t(
                "Las claves y cardinalidades se validan antes de los joins.",
                "Keys and cardinalities are validated before joins.",
                "Nøgler og kardinaliteter valideres før joins.",
            ),
            _t(
                "Los splits predictivos se realizan por paciente y respetan el tiempo índice.",
                "Predictive splits are patient-level and respect index time.",
                "Prædiktive splits udføres på patientniveau og respekterer indekstid.",
            ),
            _t(
                "El manifiesto conserva versión, semilla, configuración y checksums.",
                "The manifest retains version, seed, configuration, and checksums.",
                "Manifestet bevarer version, seed, konfiguration og checksums.",
            ),
        ),
        (
            _t(
                "Tratar encuentros como pacientes independientes.",
                "Treating encounters as independent patients.",
                "At behandle encounters som uafhængige patienter.",
            ),
            _t(
                "Asumir que synthetic significa clínicamente representativo.",
                "Assuming synthetic means clinically representative.",
                "At antage at syntetisk betyder klinisk repræsentativt.",
            ),
            _t(
                "Unir tablas de eventos sin auditar la multiplicación de filas.",
                "Joining event tables without auditing row multiplication.",
                "At joine hændelsestabeller uden audit af rækkemultiplikation.",
            ),
            _t(
                "Usar eventos posteriores al tiempo de predicción.",
                "Using events recorded after prediction time.",
                "At bruge hændelser registreret efter prædiktionstidspunktet.",
            ),
        ),
        (
            _t(
                "¿Qué representa una fila antes y después de cada transformación?",
                "What does one row represent before and after each transformation?",
                "Hvad repræsenterer én række før og efter hver transformation?",
            ),
            _t(
                "¿Qué cardinalidad esperabas y qué conteo la confirma?",
                "What cardinality did you expect and which count confirms it?",
                "Hvilken kardinalitet forventede du, og hvilket antal bekræfter den?",
            ),
            _t(
                "¿Qué información estaba disponible en el tiempo índice?",
                "Which information was available at index time?",
                "Hvilken information var tilgængelig ved indekstidspunktet?",
            ),
            _t(
                "¿Qué conclusión dejaría de ser válida con datos reales?",
                "Which conclusion would stop being valid on real data?",
                "Hvilken konklusion ville ophøre med at være gyldig på reelle data?",
            ),
        ),
        (
            _t(
                "Declara procedencia y límite de generalización.",
                "States provenance and generalization boundary.",
                "Angiver proveniens og generaliseringsgrænse.",
            ),
            _t(
                "Valida claves, granularidad y cardinalidad.",
                "Validates keys, grain, and cardinality.",
                "Validerer nøgler, granularitet og kardinalitet.",
            ),
            _t(
                "Preserva paciente y tiempo en agregación y validación.",
                "Preserves patient and time in aggregation and validation.",
                "Bevarer patient og tid i aggregering og validering.",
            ),
            _t(
                "Produce un flujo reproducible con comprobaciones auditables.",
                "Produces a reproducible workflow with auditable checks.",
                "Producerer et reproducerbart workflow med auditerbare kontroller.",
            ),
        ),
        (
            _t(
                "No presentar Synthea como datos de pacientes reales.",
                "Do not present Synthea as real-patient data.",
                "Præsenter ikke Synthea som data fra virkelige patienter.",
            ),
            _t(
                "No inventar columnas, códigos o relaciones que no estén en el contrato declarado.",
                "Do not invent columns, codes, or relations absent from the declared contract.",
                "Opfind ikke kolonner, koder eller relationer, som ikke findes i den deklarerede kontrakt.",
            ),
            _t(
                "No convertir rendimiento sintético en una afirmación clínica.",
                "Do not turn synthetic performance into a clinical claim.",
                "Gør ikke syntetisk præstation til en klinisk påstand.",
            ),
            _t(
                "Responder en el idioma activo y conservar nombres técnicos de archivos y campos.",
                "Respond in the active language and preserve technical file and field names.",
                "Svar på det aktive sprog og bevar tekniske fil- og feltnavne.",
            ),
        ),
        (
            "https://odin.sdu.dk/sitecore/index.php?a=searchfagbesk&internkode=BMB831&lang=en",
            "https://github.com/synthetichealth/synthea",
            "https://github.com/synthetichealth/synthea/wiki/CSV-File-Data-Dictionary",
            "https://doi.org/10.1093/jamia/ocx079",
        ),
    ),
)

LOCALIZED_MODULE_01_SYNTHEA_WORKFLOWS = build_module(_SPEC)
LOCALIZED_OBJECTIVE_QUESTION_BANK_01 = build_question_bank(_SPEC)


def materialize_module_01_question_bank(
    locale: AppLocale | str = AppLocale.SPANISH_SPAIN,
) -> tuple[AssessmentItem, ...]:
    """Materialize the stable module 1 objective bank."""

    return materialize_bank(LOCALIZED_OBJECTIVE_QUESTION_BANK_01, locale)


MODULE_01_SYNTHEA_WORKFLOWS: LearningModule = LOCALIZED_MODULE_01_SYNTHEA_WORKFLOWS.materialize(
    AppLocale.SPANISH_SPAIN
)
OBJECTIVE_QUESTION_BANK_01 = materialize_module_01_question_bank()

__all__ = [
    "LOCALIZED_MODULE_01_SYNTHEA_WORKFLOWS",
    "LOCALIZED_OBJECTIVE_QUESTION_BANK_01",
    "MODULE_01_SYNTHEA_WORKFLOWS",
    "OBJECTIVE_QUESTION_BANK_01",
    "materialize_module_01_question_bank",
]
